version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - PORT=10000
      - HOST=0.0.0.0
    build: ./
    ports:
      - '10000:10000'
